services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wallet_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ./migrations:/liquibase/migrations
    environment:
      - CHANGELOG_FILE=migrations/changelog-master.xml
    command: --url=jdbc:postgresql://db:5432/wallet_management --username=user --password=password --changeLogFile=migrations/changelog-master.xml update
    depends_on:
      - db

  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT}'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      
  tests:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pytest tests'  # Добавляем задержку перед выполнением тестов
    depends_on:
      - app  # Убедитесь, что приложение запущено перед тестами

volumes:
  postgres_data:
